/**
 * Líderes Colbeef 2026 — fuente única para formularios del proyecto.
 * Misma lista que en Radicar Solicitud de Contrato.
 */

export const LIDERES_COLBEEF = [
    { id: "1977852", label: "RINCON SARMIENTO CARLOS ANDRES - DIRECTOR NEGOCIOS GANADEROS" },
    { id: "80424220", label: "HERNANDEZ URZOLA ROBERTO CARLOS - DIRECTOR COMERCIAL" },
    { id: "13542263", label: "SERRANO ARDILA DIEGO FERNANDO - DIRECTOR ADMINISTRATIVO Y FINANCIERO" },
    { id: "37747995", label: "GOMEZ MARTINEZ NIDIA ROCIO - DIRECTORA DE ASUNTOS CORPORATIVOS" },
    { id: "1098673651", label: "PINEDA TRIANA VIVIANA ANDREA - JEFE DE TESORERIA Y CARTERA" },
    { id: "79249780", label: "ARDILA JIMENEZ DIEGO SIGIFREDO - GERENTE GENERAL" },
    { id: "1127947335", label: "RINCON BOTELLO YERSON JAVIER - LIDER DE BENEFICIO" },
    { id: "91536323", label: "DIAZ HIGUERA LUIS FERNANDO - JEFE DE VENTAS" },
    { id: "73579178", label: "LARA LUNA LEONARDO LUIS - JEFE DE TECNOLOGIA" },
    { id: "1098660251", label: "ARENAS SARMIENTO FAUSTO ANDRES - LIDER CRECIMIENTO COMERCIAL" },
    { id: "91477701", label: "VARGAS DURAN ROBINSON - LIDER DE DESPOSTE" },
    { id: "1098763171", label: "SUAREZ QUIÑONES JEFFERSON ALEXANDER - LIDER SST" },
    { id: "1056908061", label: "SEGURA BARRERA MARIA FILOMENA - DIRECTORA DE PLANTA" },
    { id: "1098661407", label: "VERA MORA CINDY LEOMAR - JEFE DE GESTION HUMANA" },
    { id: "63560912", label: "RUBIANO LEMUS YUDY ANDREA - JEFE DE CALIDAD" },
    { id: "1102387740", label: "LIZARAZO PARADA DIEGO FERNANDO - LIDER DE PLANILLAJE" },
    { id: "43536705", label: "OSORIO ESTRADA LILIANA MARIA - JEFE DE CONTABILIDAD" },
    { id: "1098738467", label: "ROMERO PEDRAZA SERGIO OMAR - JEFE DE PRODUCCION" },
    { id: "1095807041", label: "BARAJAS MAYORGA WILMER DARIO - LIDER LOGISTICA" },
    { id: "1098661799", label: "RUEDA MADERO PAOLA CAROLINA - LIDER DE VENTAS" },
    { id: "52822147", label: "MUÑOZ BERNAL PAOLA ANDREA - JEFE DE MERCADEO" },
    { id: "1098665901", label: "RODRIGUEZ RUIZ ALEXANDER - JEFE DE PLANEACION FINANCIERA" },
    { id: "1098725715", label: "QUESADA ZORRILLA WILHELM ARLEY - DIRECTOR CONTROLLER" },
];
